### ISSUE TITLE
Use rxjs Single instead of Subject for Load calls?

### ISSUE THREAD

**Issue by steve-haar** [vintage-software/vstack-graph#17]
Our completion$ subject only emits one value and then completes. If I subscribe to this in an angular 2 component, do I still have to unsubscribe in ngOnDestroy since I know it will never emit again? Anyway, to make this explicit, I think we should use a Single instead of a Subject. Surely you wouldn't have to unsubscribe to a single, right?

**Comment by splintercode** [comment]
Unless I am missing something it looks like rxjs5 does not have a Single object. Looks like for now we will have to sick with the Subject.
