### ISSUE TITLE
Rename GraphService?

### ISSUE THREAD

**Issue by steve-haar** [vintage-software/vstack-graph#23]
I would like to have a GraphService class that inherits from the Vstack Graph class. I could name it AppGraphService, but since there will only be one we typically prefer to not prefix files or classes with the name of the app. This will also help when comparing code from one project to the next. I'm not sure what we'd rename it to. Maybe BaseGraphService?

For now I'm using this: import {GraphService as BaseGraphService} from 'vstack-graph'; so maybe we don't need to rename it.

**Comment by splintercode** [comment]
Rename sounds reasonable. I'd like to document some recommended naming conventions as well. Tackle this first thing in the morning.
